include:
  - board: corne_choc_pro_left
    snippet: studio-rpc-usb-uart
    cmake-args: -DCONFIG_ZMK_POINTING=y
  - board: corne_choc_pro_right
    snippet: studio-rpc-usb-uart
    cmake-args: -DCONFIG_ZMK_POINTING=y
